import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Planos.module.css';
import { useSubscriberContext } from '../src/context/Subscriber/SubscriberContext';
import CardPlanos from '../src/components/Card';
import BoxCard from '../src/components/BoxCard';
import { Button, Container } from 'reactstrap';
import { coRotaInscrito, coRotaPlanos } from '../src/Constantes';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../src/services/api';
import { TInscritoPedido, TPlans } from '../src/types';
import Header from '../src/components/Header';
import Router from 'next/router';

const AssinaturaRealizada: NextPage = () => {
  const { inscrito } = useSubscriberContext();

  const [Order, setOrder] = useState<TInscritoPedido>();
  const [planos, setPlanos] = useState<Array<TPlans>>([]);

  const handleVoltar = () => {
    Router.push('/Planos');
  };

  const LoadPlanos = useCallback(async () => {
    const res = await api.get(`${coRotaPlanos}`);
    if (res.data) {
      setPlanos(res.data);
    }
  }, []);

  useEffect(() => {
    LoadPlanos();
  }, [LoadPlanos]);

  const LoadInscritoOrder = useCallback(async () => {
    //@ts-ignore

    const res = await api.get(`${coRotaInscrito}/${inscrito?.id}`);

    if (res.data) {
      setOrder(res.data);
    }
  }, [inscrito]);

  useEffect(() => {
    LoadInscritoOrder();
  }, [LoadInscritoOrder]);

  return (
    <>
      <Head>
        <title>Wa Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      {/* colocar logo da waproject  e nome e email */}

      <section className={styles.assinar}>
        <h1 className={styles.title}>ASSINATURA REALIZADA COM SUCESSO</h1>
        <h2>Plano Escolhido</h2>
        <Container className={styles.container}>
          <BoxCard
            planos={planos.filter(
              plano => plano.id === Order?.Order[0]?.plan.id
            )}
            Order={Order}
          />
        </Container>
        <div className={styles.buttonContainer}>
          <Button
            onClick={() => {
              handleVoltar();
            }}
            className={styles.buttonVerPlanos}
          >
            <span>Visualizar Planos</span>
          </Button>
        </div>
      </section>
    </>
  );
};

export default AssinaturaRealizada;
