import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Planos.module.css';
import { useSubscriberContext } from '../src/context/Subscriber/SubscriberContext';
import CardPlanos from '../src/components/Card';
import BoxCard from '../src/components/BoxCard';
import { Button, Container } from 'reactstrap';
import { coRotaPlanos } from '../src/Constantes';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../src/services/api';
import { TPlans } from '../src/types';
const Planos: NextPage = () => {
  const { inscrito } = useSubscriberContext();
  const [mostrarSectionAssinar, setMostrarSectionAssinar] = useState(false);
  const [planos, setPlanos] = useState<Array<TPlans>>([]);

  const handleAssinar = () => {
    setMostrarSectionAssinar(!mostrarSectionAssinar);
  };

  const LoadPlanos = useCallback(async () => {
    const res = await api.get(`${coRotaPlanos}`);
    if (res.data) {
      console.log(res.data);
      setPlanos(res.data);
    }
  }, []);

  useEffect(() => {
    LoadPlanos();
  }, []);

  return (
    <>
      <Head>
        <title>Wa Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className={styles.header}>
        {/* colocar logo da waproject  e nome e email */}
        <Image src='/logo.svg' width={200} height={100} />
        <div className={styles.subscriber}>
          <h5>{`Nome:${inscrito?.name}`}</h5>
          <h5> {`Email:${inscrito?.email}`}</h5>
        </div>
      </header>

      {!mostrarSectionAssinar ? (
        <section className={styles.sectionComparar}>
          <h1 className={styles.title}>COMPARE OS PLANOS DE ASSINATURA</h1>
          <Container className={styles.container}>
            {planos.map((plano, index) => (
              <CardPlanos index={index} key={plano.id} {...plano} />
            ))}
          </Container>
          <div className={styles.buttonContainer}>
            <Button
              onClick={() => {
                handleAssinar();
              }}
              className={styles.buttonVerPlanos}
            >
              <span>Veja os planos de assinatura disponíveis</span>
            </Button>
          </div>
        </section>
      ) : (
        <section className={styles.assinar}>
          <h1 className={styles.title}>ESCOLHA SEU PLANO DE ASSINATURA</h1>
          <span>
            Escolha entre três novas opções de assinatura para obter os jogos e
            os benefícios desejados.
          </span>
          <Container className={styles.container}>
            <BoxCard planos={planos} />
          </Container>
          <div className={styles.buttonContainer}>
            <Button
              onClick={() => {
                handleAssinar();
              }}
              className={styles.buttonVerPlanos}
            >
              <span>Comparar os Planos</span>
            </Button>
          </div>
        </section>
      )}
    </>
  );
};

export default Planos;
