import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Planos.module.css';
import { useSubscriberContext } from '../src/context/Subscriber/SubscriberContext';
import CardPlanos from '../src/components/Card';
import BoxCard from '../src/components/BoxCard';
import { Button, Container } from 'reactstrap';
import { coRotaInscrito, coRotaPlanos } from '../src/Constantes';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../src/services/api';
import { TInscritoPedido, TPlans } from '../src/types';
import Header from '../src/components/Header';
const Planos: NextPage = () => {
  const { inscrito } = useSubscriberContext();
  const [mostrarSectionAssinar, setMostrarSectionAssinar] = useState(false);
  const [Order, setOrder] = useState<TInscritoPedido>();
  const [planos, setPlanos] = useState<Array<TPlans>>([]);

  const handleAssinar = () => {
    setMostrarSectionAssinar(!mostrarSectionAssinar);
  };

  const LoadInscritoOrder = useCallback(async () => {
    //@ts-ignore

    const res = await api.get(`${coRotaInscrito}/${inscrito?.id}`);

    if (res.data) {
      setOrder(res.data);
    }
  }, [inscrito]);

  useEffect(() => {
    LoadInscritoOrder();
  }, [LoadInscritoOrder]);
  const LoadPlanos = useCallback(async () => {
    const res = await api.get(`${coRotaPlanos}`);
    if (res.data) {
      setPlanos(res.data);
    }
  }, []);

  useEffect(() => {
    LoadPlanos();
  }, [LoadPlanos]);

  useEffect(() => {
    if (Order?.Order[0]?.plan.id) {
      setMostrarSectionAssinar(true);
    }
  }, [Order]);
  return (
    <>
      <Head>
        <title>Wa Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      {!mostrarSectionAssinar ? (
        <section className={styles.sectionComparar}>
          <h1 className={styles.title}>COMPARE OS PLANOS DE ASSINATURA</h1>
          <Container className={styles.container}>
            {planos.map((plano, index) => (
              <CardPlanos index={index} key={plano.id} {...plano} />
            ))}
          </Container>
          <div className={styles.buttonContainer}>
            <Button
              onClick={() => {
                handleAssinar();
              }}
              className={styles.buttonVerPlanos}
            >
              <span>Veja os planos de assinatura disponíveis</span>
            </Button>
          </div>
        </section>
      ) : (
        <section className={styles.assinar}>
          <h1 className={styles.title}>ESCOLHA SEU PLANO DE ASSINATURA</h1>
          <span>
            Escolha entre três novas opções de assinatura para obter os jogos e
            os benefícios desejados.
          </span>
          <Container className={styles.container}>
            <BoxCard planos={planos} Order={Order} />
          </Container>
          <div className={styles.buttonContainer}>
            <Button
              onClick={() => {
                handleAssinar();
              }}
              className={styles.buttonVerPlanos}
            >
              <span>Comparar os Planos</span>
            </Button>
          </div>
        </section>
      )}
    </>
  );
};

export default Planos;
