import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Planos.module.css';
import { useSubscriberContext } from '../src/context/Subscriber/SubscriberContext';
import CardPlanos from '../src/components/Card';
import { Button, Container } from 'reactstrap';
import { planos } from '../src/Constantes';
const Planos: NextPage = () => {
  const { inscrito } = useSubscriberContext();
  return (
    <>
      <Head>
        <title>Wa Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className={styles.header}>
        {/* colocar logo da waproject  e nome e email */}
        <Image src='/logo.svg' width={200} height={100} />
        <div className={styles.subscriber}>
          <h5>{`Nome:${inscrito?.name}`}</h5>
          <h5> {`Email:${inscrito?.email}`}</h5>
        </div>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>COMPARE OS PLANOS DE ASSINATURA</h1>
        <Container className={styles.container}>
          {planos.map(plano => (
            <CardPlanos key={plano.id} {...plano} />
          ))}

          {/* botao para assinar os planos */}
        </Container>
        <div className={styles.buttonContainer}>
          <Button type='submit' className={styles.buttonVerPlanos}>
            <span>Veja os planos de assinatura disponíveis</span>
          </Button>
        </div>
      </main>
    </>
  );
};

export default Planos;
