import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useSubscriberContext } from '../../context/Subscriber/SubscriberContext';
import styles from '../../../styles/Planos.module.css';

const Header: NextPage = () => {
  const { inscrito } = useSubscriberContext();

  return (
    <>
      <Head>
        <title>Wa Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className={styles.header}>
        {/* colocar logo da waproject  e nome e email */}
        <Image src='/logo.svg' width={200} height={100} />
        <div className={styles.subscriber}>
          <h5>{`Nome:${inscrito?.name}`}</h5>
          <h5> {`Email:${inscrito?.email}`}</h5>
        </div>
      </header>
    </>
  );
};
export default Header;
